name: lifelinkai
description: "A Blood Donation Mobile App for saving lives!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  curved_navigation_bar: ^1.0.3
  
  # UI packages
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff" # Couleur de fond (optionnel)
  adaptive_icon_foreground: "assets/icons/icon.png" # Icône adaptable Android
flutter:
  uses-material-design: true 

  assets:
    - assets/
    - assets/underline.png
    - assets/HomePagePic.png

